-- ----------------------------------------------------------------------------- 
--  Potions 
-- These contain dictionaries with the potions that are craftable 
-- Theese use recipes generated by the kubejs scripts within the /KubeJSScripts folder
-- -----------------------------------------------------------------------------
-- Do not edit line 6 
local Potions = {}

-- Vanilla Potions Base 
Potions.VANILLA_POTIONS_BASE = {{
    -- Night Vision Potion 
    result = "kubejs:night_vision",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:golden_carrot"
}, {
    -- Invisibility Potion 
    result = "kubejs:invisibility",
    base_potion = "kubejs:night_vision",
    ingredient = "minecraft:fermented_spider_eye"
}, {
    -- Leaping Potion 
    result = "kubejs:leaping",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:rabbit_foot"
}, {
    -- Fire Resistance Potion 
    result = "kubejs:fire_resistance",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:magma_cream"
}, {
    -- Swiftness Potion 
    result = "kubejs:swiftness",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:sugar"
}, {
    -- Slowness Potion 
    result = "kubejs:slowness",
    base_potion = "kubejs:swiftness",
    ingredient = "minecraft:fermented_spider_eye"
}, {
    -- Turtle Master Potion 
    result = "kubejs:turtle_master",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:turtle_shell"
}, {
    -- Water Breathing Potion 
    result = "kubejs:water_breathing",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:pufferfish"
}, {
    -- Harming Potion 
    result = "kubejs:harming",
    base_potion = "kubejs:healing",
    ingredient = "minecraft:fermented_spider_eye"
}, {
    -- Poison Potion 
    result = "kubejs:poison",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:spider_eye"
}, {
    -- Regeneration Potion 
    result = "kubejs:regeneration",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:ghast_tear"
}, {
    -- Strength Potion 
    result = "kubejs:strength",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:blaze_powder"
}, {
    -- Luck Potion 
    result = "kubejs:luck",
    base_potion = "kubejs:awkward",
    ingredient = "apotheosis:lucky_foot"
}, {
    -- Slow Falling Potion 
    result = "kubejs:slow_falling",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:phantom_membrane"
}, {
    -- Healing Potion 
    result = "kubejs:healing",
    base_potion = "kubejs:mundane",
    ingredient = "minecraft:glistering_melon_slice"
}, {
    -- Weakness Potion 
    result = "kubejs:weakness",
    base_potion = "kubejs:mundane",
    ingredient = "minecraft:fermented_spider_eye"
}, {
    result = "kubejs:long_night_vision",
    base_potion = "kubejs:night_vision",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_invisibility",
    base_potion = "kubejs:invisibility",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_leaping",
    base_potion = "kubejs:leaping",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_fire_resistance",
    base_potion = "kubejs:fire_resistance",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_turtle_master",
    base_potion = "kubejs:turtle_master",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_swiftness",
    base_potion = "kubejs:swiftness",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_slowness",
    base_potion = "kubejs:slowness",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_weakness",
    base_potion = "kubejs:weakness",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_slow_falling",
    base_potion = "kubejs:slow_falling",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_water_breathing",
    base_potion = "kubejs:water_breathing",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_regeneration",
    base_potion = "kubejs:regeneration",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_strength",
    base_potion = "kubejs:strength",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:long_poison",
    base_potion = "kubejs:poison",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_swiftness",
    base_potion = "kubejs:swiftness",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:strong_strength",
    base_potion = "kubejs:strength",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:strong_regeneration",
    base_potion = "kubejs:regeneration",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:strong_poison",
    base_potion = "kubejs:poison",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:strong_healing",
    base_potion = "kubejs:healing",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:strong_harming",
    base_potion = "kubejs:harming",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:strong_turtle_master",
    base_potion = "kubejs:turtle_master",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:strong_leaping",
    base_potion = "kubejs:leaping",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:strong_slowness",
    base_potion = "kubejs:slowness",
    ingredient = "minecraft:glowstone_dust"
}}

-- Potion Bases 
Potions.BASE_POTIONS = {{
    -- Mundane Potion 
    result = "kubejs:mundane",
    base_potion = "minecraft:water",
    ingredient = "minecraft:redstone"
}, {
    -- Awkward Potion 
    result = "kubejs:awkward",
    base_potion = "minecraft:water",
    ingredient = "minecraft:nether_wart"
}}

Potions.CORAIL_TOMBSTONE = {{
    result = "kubejs:spectral",
    base_potion = "kubejs:awkward",
    ingredient = "tombstone:grave_dust"
}, {
    result = "kubejs:bait",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:rabbit_foot"
}, {
    result = "kubejs:frostbite",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:magma_cream"
}, {
    result = "kubejs:darkness",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:sugar"
}, {
    result = "kubejs:discretion",
    base_potion = "kubejs:swiftness",
    ingredient = "minecraft:fermented_spider_eye"
}, {
    result = "kubejs:restoration",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:turtle_shell"
}}

Potions.APOTHEOSIS = {{
    result = "kubejs:resistance",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:shulker_shell"
}, {
    result = "kubejs:long_resistance",
    base_potion = "kubejs:resistance",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_resistance",
    base_potion = "kubejs:resistance",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:absorption",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:golden_apple"
}, {
    result = "kubejs:long_absorption",
    base_potion = "kubejs:absorption",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_absorption",
    base_potion = "kubejs:absorption",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:haste",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:mushroom_stew"
}, {
    result = "kubejs:long_haste",
    base_potion = "kubejs:haste",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_haste",
    base_potion = "kubejs:haste",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:fatigue",
    base_potion = "kubejs:haste",
    ingredient = "minecraft:fermented_spider_eye"
}, {
    result = "kubejs:long_fatigue",
    base_potion = "kubejs:fatigue",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_fatigue",
    base_potion = "kubejs:fatigue",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:wither",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:wither_skeleton_skull"
}, {
    result = "kubejs:long_wither",
    base_potion = "kubejs:wither",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_wither",
    base_potion = "kubejs:wither",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:sundering",
    base_potion = "kubejs:resistance",
    ingredient = "minecraft:fermented_spider_eye"
}, {
    result = "kubejs:long_sundering",
    base_potion = "kubejs:sundering",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_sundering",
    base_potion = "kubejs:sundering",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:knowledge",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:experience_bottle"
}, {
    result = "kubejs:long_knowledge",
    base_potion = "kubejs:knowledge",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_knowledge",
    base_potion = "kubejs:knowledge",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:vitality",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:sweet_berries"
}, {
    result = "kubejs:long_vitality",
    base_potion = "kubejs:vitality",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_vitality",
    base_potion = "kubejs:vitality",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:grievous",
    base_potion = "kubejs:vitality",
    ingredient = "minecraft:fermented_spider_eye"
}, {
    result = "kubejs:long_grievous",
    base_potion = "kubejs:grievous",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_grievous",
    base_potion = "kubejs:grievous",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:levitation",
    base_potion = "kubejs:slow_falling",
    ingredient = "minecraft:fermented_spider_eye"
}, {
    result = "kubejs:flying",
    base_potion = "kubejs:levitation",
    ingredient = "minecraft:popped_chorus_fruit"
}, {
    result = "kubejs:long_flying",
    base_potion = "kubejs:flying",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:extra_long_flying",
    base_potion = "kubejs:flying",
    ingredient = "minecraft:glowstone_dust"
}}

Potions.UNDERGARDEN = {{
    result = "kubejs:brittleness",
    base_potion = "kubejs:awkward",
    ingredient = "undergarden:blood_globule"
}, {
    result = "kubejs:long_brittleness",
    base_potion = "kubejs:brittleness",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_brittleness",
    base_potion = "kubejs:brittleness",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:featherweight",
    base_potion = "kubejs:awkward",
    ingredient = "undergarden:veil_mushroom"
}, {
    result = "kubejs:long_featherweight",
    base_potion = "kubejs:featherweight",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_featherweight",
    base_potion = "kubejs:featherweight",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:virulent_resistance",
    base_potion = "kubejs:awkward",
    ingredient = "undergarden:gloomgourd"
}, {
    result = "kubejs:long_virulent_resistance",
    base_potion = "kubejs:virulent_resistance",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:glowing",
    base_potion = "kubejs:awkward",
    ingredient = "undergarden:droopvine_item"
}, {
    result = "kubejs:long_glowing",
    base_potion = "kubejs:glowing",
    ingredient = "minecraft:redstone"
}}

Potions.IRONS_SPELLBOOKS = {{
    result = "kubejs:instant_mana_one",
    base_potion = "kubejs:awkward",
    ingredient = "irons_spellbooks:arcane_essence"
}, {
    result = "kubejs:instant_mana_two",
    base_potion = "kubejs:instant_mana_one",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:instant_mana_three",
    base_potion = "kubejs:instant_mana_two",
    ingredient = "minecraft:amethyst_shard"
}, {
    result = "kubejs:instant_mana_four",
    base_potion = "kubejs:instant_mana_three",
    ingredient = "minecraft:amethyst_cluster"
}}

Potions.ECOLOGICS = {{
    result = "kubejs:sliding",
    base_potion = "kubejs:awkward",
    ingredient = "ecologics:penguin_feather"
}, {
    result = "kubejs:long_sliding",
    base_potion = "kubejs:sliding",
    ingredient = "minecraft:redstone"
}}

Potions.ARS_NOUVEAU = {{
    result = "kubejs:mana_regen_potion",
    base_potion = "kubejs:awkward",
    ingredient = "ars_nouveau:sourceberry_bush"
}, {
    result = "kubejs:mana_regen_potion_long",
    base_potion = "kubejs:mana_regen_potion",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:mana_regen_potion_strong",
    base_potion = "kubejs:mana_regen_potion",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:spell_damage_potion",
    base_potion = "kubejs:awkward",
    ingredient = "ars_nouveau:magebloom"
}, {
    result = "kubejs:spell_damage_potion_long",
    base_potion = "kubejs:spell_damage_potion",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:spell_damage_potion_strong",
    base_potion = "kubejs:spell_damage_potion",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:recovery_potion",
    base_potion = "kubejs:awkward",
    ingredient = "ars_nouveau:mendosteen_pod"
}, {
    result = "kubejs:recovery_potion_long",
    base_potion = "kubejs:recovery_potion",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:recovery_potion_strong",
    base_potion = "kubejs:recovery_potion",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:blasting_potion",
    base_potion = "kubejs:awkward",
    ingredient = "ars_nouveau:bombegranate_pod"
}, {
    result = "kubejs:blasting_potion_long",
    base_potion = "kubejs:blasting_potion",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:blasting_potion_strong",
    base_potion = "kubejs:blasting_potion",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:freezing_potion",
    base_potion = "kubejs:awkward",
    ingredient = "ars_nouveau:frostaya_pod"
}, {
    result = "kubejs:freezing_potion_long",
    base_potion = "kubejs:freezing_potion",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:freezing_potion_strong",
    base_potion = "kubejs:freezing_potion",
    ingredient = "minecraft:glowstone_dust"
}, {
    result = "kubejs:shielding_potion",
    base_potion = "kubejs:awkward",
    ingredient = "ars_nouveau:bastion_pod"
}, {
    result = "kubejs:shielding_potion_long",
    base_potion = "kubejs:shielding_potion",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:shielding_potion_strong",
    base_potion = "kubejs:shielding_potion",
    ingredient = "minecraft:glowstone_dust"
}}

Potions.ARS_ELEMENTAL = {{
    result = "kubejs:enderference_potion",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:twisting_vines"
}, {
    result = "kubejs:enderference_potion_long",
    base_potion = "kubejs:enderference_potion",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:shock_potion",
    base_potion = "kubejs:awkward",
    ingredient = "ars_elemental:flashpine_pod"
}, {
    result = "kubejs:shock_potion_long",
    base_potion = "kubejs:shock_potion",
    ingredient = "minecraft:redstone"
}}

Potions.EIDOLON = {{
    result = "kubejs:undeath",
    base_potion = "kubejs:awkward",
    ingredient = "eidolon:death_essence"
}, {
    result = "kubejs:long_undeath",
    base_potion = "kubejs:undeath",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:vulnerable",
    base_potion = "kubejs:awkward",
    ingredient = "eidolon:tattered_cloth"
}, {
    result = "kubejs:long_vulnerable",
    base_potion = "kubejs:vulnerable",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_vulnerable",
    base_potion = "kubejs:vulnerable",
    ingredient = "minecraft:glowstone"
}, {
    result = "kubejs:reinforced",
    base_potion = "kubejs:awkward",
    ingredient = "minecraft:nautilus_shell"
}, {
    result = "kubejs:long_reinforced",
    base_potion = "kubejs:reinforced",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_reinforced",
    base_potion = "kubejs:reinforced",
    ingredient = "minecraft:glowstone"
}, {
    result = "kubejs:anchored",
    base_potion = "kubejs:awkward",
    ingredient = "eidolon:warped_sprouts"
}, {
    result = "kubejs:long_anchored",
    base_potion = "kubejs:anchored",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:chilled",
    base_potion = "kubejs:awkward",
    ingredient = "eidolon:wraith_heart"
}, {
    result = "kubejs:long_chilled",
    base_potion = "kubejs:chilled",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:decay",
    base_potion = "kubejs:awkward",
    ingredient = "eidolon:withered_heart"
}, {
    result = "kubejs:long_decay",
    base_potion = "kubejs:decay",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_decay",
    base_potion = "kubejs:decay",
    ingredient = "minecraft:glowstone"
}}

Potions.NATURALIST = {{
    result = "kubejs:forest_dasher",
    base_potion = "kubejs:awkward",
    ingredient = "naturalist:antler"
}, {
    result = "kubejs:long_forest_dasher",
    base_potion = "kubejs:forest_dasher",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_forest_dasher",
    base_potion = "kubejs:forest_dasher",
    ingredient = "minecraft:glowstone_dust"
}}

Potions.POTIONS_MASTER = {{
    result = "kubejs:coal_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedcoal_powder"
}, {
    result = "kubejs:iron_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatediron_powder"
}, {
    result = "kubejs:redstone_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedredstone_powder"
}, {
    result = "kubejs:lapis_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedlapis_powder"
}, {
    result = "kubejs:gold_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedgold_powder"
}, {
    result = "kubejs:diamond_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinateddiamond_powder"
}, {
    result = "kubejs:emerald_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedemerald_powder"
}, {
    result = "kubejs:aluminum_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedaluminum_powder"
}, {
    result = "kubejs:copper_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedcopper_powder"
}, {
    result = "kubejs:tin_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedtin_powder"
}, {
    result = "kubejs:nickel_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatednickel_powder"
}, {
    result = "kubejs:uranium_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinateduranium_powder"
}, {
    result = "kubejs:lead_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedlead_powder"
}, {
    result = "kubejs:silver_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedsilver_powder"
}, {
    result = "kubejs:zinc_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedzinc_powder"
}, {
    result = "kubejs:osmium_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedosmium_powder"
}, {
    result = "kubejs:quartz_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedquartz_powder"
}, {
    result = "kubejs:bismuth_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedbismuth_powder"
}, {
    result = "kubejs:crimsoniron_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedcrimsoniron_powder"
}, {
    result = "kubejs:platinum_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedplatinum_powder"
}, {
    result = "kubejs:netherite_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatednetherite_powder"
}, {
    result = "kubejs:allthemodium_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedallthemodium_powder"
}, {
    result = "kubejs:vibranium_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedvibranium_powder"
}, {
    result = "kubejs:unobtainium_sight",
    base_potion = "kubejs:mundane",
    ingredient = "potionsmaster:calcinatedunobtainium_powder"
}}

Potions.DEEPER_DARKER = {{
    result = "kubejs:sculk_affinity",
    base_potion = "kubejs:awkward",
    ingredient = "deeperdarker:soul_crystal"
}, {
    result = "kubejs:long_sculk_affinity",
    base_potion = "kubejs:sculk_affinity",
    ingredient = "minecraft:redstone"
}}

Potions.AUTUMNITY = {{
    result = "kubejs:extension",
    base_potion = "kubejs:awkward",
    ingredient = "autumnity:snail_goo"
}}

Potions.QUARK = {{
    result = "kubejs:resilience",
    base_potion = "kubejs:awkward",
    ingredient = "quark:crab_shell"
}, {
    result = "kubejs:long_resilience",
    base_potion = "kubejs:resilience",
    ingredient = "minecraft:redstone"
}, {
    result = "kubejs:strong_resilience",
    base_potion = "kubejs:resilience",
    ingredient = "minecraft:glowstone_dust"
}}

return Potions
