-- ----------------------------------------------------------------------------- 
--  Potions 
-- These contain dictionaries with the potions that are craftable 
-- Theese use recipes generated by the kubejs scripts within the /KubeJSScripts folder
-- -----------------------------------------------------------------------------

-- Do not edit line 6 
local Potions = {}

-- Vanilla Potions Base 
Potions.VANILLA_POTIONS_BASE = { 
    { 
        -- Night Vision Potion 
        potion = "kubejs:night_vision", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:golden_carrot",
    }, 
   
    { 
        -- Invisibility Potion 
        potion = "kubejs:invisibility", 
        base_potion = "kubejs:night_vision", 
        ingredient = "minecraft:fermented_spider_eye",
    }, 
    
    { 
        -- Leaping Potion 
        potion = "kubejs:leaping", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:rabbit_foot",
    }, 
    { 
        -- Fire Resistance Potion 
        potion = "kubejs:fire_resistance", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:magma_cream",
    },  
    { 
        -- Swiftness Potion 
        potion = "kubejs:swiftness", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:sugar",
    }, 
    { 
        -- Slowness Potion 
        potion = "kubejs:slowness", 
        base_potion = "kubejs:swiftness", 
        ingredient = "minecraft:fermented_spider_eye",
    }, 
    { 
        -- Turtle Master Potion 
        potion = "kubejs:turtle_master", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:turtle_shell",
    }, 
    { 
        -- Water Breathing Potion 
        potion = "kubejs:water_breathing", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:pufferfish",
    }, 
    { 
        -- Harming Potion 
        potion = "kubejs:harming", 
        base_potion = "kubejs:healing", 
        ingredient = "minecraft:fermented_spider_eye",
    }, 
    { 
        -- Poison Potion 
        potion = "kubejs:poison", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:spider_eye",
    }, 
    { 
        -- Regeneration Potion 
        potion = "kubejs:regeneration", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:ghast_tear",
    }, 
    { 
        -- Strength Potion 
        potion = "kubejs:strength", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:blaze_powder",
    }, 
    { 
        -- Luck Potion 
        potion = "kubejs:luck", 
        base_potion = "kubejs:awkward", 
        ingredient = "apotheosis:lucky_foot",
    }, 
    { 
        -- Slow Falling Potion 
        potion = "kubejs:slow_falling", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:phantom_membrane",
    }, 
    { 
        -- Healing Potion 
        potion = "kubejs:healing", 
        base_potion = "kubejs:mundane", 
        ingredient = "minecraft:glistering_melon_slice",
    }, 
    { 
        -- Weakness Potion 
        potion = "kubejs:weakness", 
        base_potion = "kubejs:mundane", 
        ingredient = "minecraft:fermented_spider_eye",
    },
     {
        potion = "kubejs:long_night_vision", 
        base_potion = "kubejs:night_vision", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_invisibility", 
        base_potion = "kubejs:invisibility", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_leaping", 
        base_potion = "kubejs:leaping", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_fire_resistance", 
        base_potion = "kubejs:fire_resistance", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_turtle_master", 
        base_potion = "kubejs:turtle_master", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_swiftness", 
        base_potion = "kubejs:swiftness", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_slowness", 
        base_potion = "kubejs:slowness", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_weakness", 
        base_potion = "kubejs:weakness", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_slow_falling", 
        base_potion = "kubejs:slow_falling", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_water_breathing", 
        base_potion = "kubejs:water_breathing", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_regeneration", 
        base_potion = "kubejs:regeneration", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_strength", 
        base_potion = "kubejs:strength", 
        ingredient = "minecraft:redstone",
    }, 
    {
        potion = "kubejs:long_poison", 
        base_potion = "kubejs:poison", 
        ingredient = "minecraft:redstone",
    },
    {
        potion = "kubejs:strong_swiftness", 
        base_potion = "kubejs:swiftness", 
        ingredient = "minecraft:glowstone_dust",
    }, 
    {
        potion = "kubejs:strong_strength", 
        base_potion = "kubejs:strength", 
        ingredient = "minecraft:glowstone_dust",
    }, 
    {
        potion = "kubejs:strong_regeneration", 
        base_potion = "kubejs:regeneration", 
        ingredient = "minecraft:glowstone_dust",
    }, 
    {
        potion = "kubejs:strong_poison", 
        base_potion = "kubejs:poison", 
        ingredient = "minecraft:glowstone_dust",
    }, 
    {
        potion = "kubejs:strong_healing", 
        base_potion = "kubejs:healing", 
        ingredient = "minecraft:glowstone_dust",
    }, 
    {
        potion = "kubejs:strong_harming", 
        base_potion = "kubejs:harming", 
        ingredient = "minecraft:glowstone_dust",
    }, 
    {
        potion = "kubejs:strong_turtle_master", 
        base_potion = "kubejs:turtle_master", 
        ingredient = "minecraft:glowstone_dust",
    }, 
    {
        potion = "kubejs:strong_leaping", 
        base_potion = "kubejs:leaping", 
        ingredient = "minecraft:glowstone_dust",
    }, 
    {
        potion = "kubejs:strong_slowness", 
        base_potion = "kubejs:slowness", 
        ingredient = "minecraft:glowstone_dust",
    },
}

-- Potion Bases 
Potions.BASE_POTIONS = { 
    { 
        -- Mundane Potion 
        potion = "kubejs:mundane", 
        base_potion = "minecraft:water", 
        ingredient = "minecraft:redstone",
    }, 
    { 
        -- Awkward Potion 
        potion = "kubejs:awkward", 
        base_potion = "minecraft:water", 
        ingredient = "minecraft:nether_wart",
    },
} 

Potions.CORAIL_TOMBSTONE = {{
        potion = "kubejs:spectral", 
        base_potion = "kubejs:awkward", 
        ingredient = "tombstone:grave_dust",
    }, {
        potion = "kubejs:bait", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:rabbit_foot",
    }, {
        potion = "kubejs:frostbite", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:magma_cream",
    }, {
        potion = "kubejs:darkness", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:sugar",
    }, {
        potion = "kubejs:discretion", 
        base_potion = "kubejs:swiftness", 
        ingredient = "minecraft:fermented_spider_eye",
    }, {
        potion = "kubejs:restoration", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:turtle_shell",
    }, 
}

Potions.APOTHEOSIS = {{
        potion = "kubejs:resistance", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:shulker_shell",
    }, {
        potion = "kubejs:long_resistance", 
        base_potion = "kubejs:resistance", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_resistance", 
        base_potion = "kubejs:resistance", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:absorption", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:golden_apple",
    }, {
        potion = "kubejs:long_absorption", 
        base_potion = "kubejs:absorption", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_absorption", 
        base_potion = "kubejs:absorption", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:haste", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:mushroom_stew",
    }, {
        potion = "kubejs:long_haste", 
        base_potion = "kubejs:haste", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_haste", 
        base_potion = "kubejs:haste", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:fatigue", 
        base_potion = "kubejs:haste", 
        ingredient = "minecraft:fermented_spider_eye",
    }, {
        potion = "kubejs:long_fatigue", 
        base_potion = "kubejs:fatigue", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_fatigue", 
        base_potion = "kubejs:fatigue", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:wither", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:wither_skeleton_skull",
    }, {
        potion = "kubejs:long_wither", 
        base_potion = "kubejs:wither", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_wither", 
        base_potion = "kubejs:wither", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:sundering", 
        base_potion = "kubejs:resistance", 
        ingredient = "minecraft:fermented_spider_eye",
    }, {
        potion = "kubejs:long_sundering", 
        base_potion = "kubejs:sundering", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_sundering", 
        base_potion = "kubejs:sundering", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:knowledge", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:experience_bottle",
    }, {
        potion = "kubejs:long_knowledge", 
        base_potion = "kubejs:knowledge", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_knowledge", 
        base_potion = "kubejs:knowledge", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:vitality", 
        base_potion = "kubejs:awkward", 
        ingredient = "minecraft:sweet_berries",
    }, {
        potion = "kubejs:long_vitality", 
        base_potion = "kubejs:vitality", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_vitality", 
        base_potion = "kubejs:vitality", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:grievous", 
        base_potion = "kubejs:vitality", 
        ingredient = "minecraft:fermented_spider_eye",
    }, {
        potion = "kubejs:long_grievous", 
        base_potion = "kubejs:grievous", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_grievous", 
        base_potion = "kubejs:grievous", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:levitation", 
        base_potion = "kubejs:slow_falling", 
        ingredient = "minecraft:fermented_spider_eye",
    }, {
        potion = "kubejs:flying", 
        base_potion = "kubejs:levitation", 
        ingredient = "minecraft:popped_chorus_fruit",
    }, {
        potion = "kubejs:long_flying", 
        base_potion = "kubejs:flying", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:extra_long_flying", 
        base_potion = "kubejs:flying", 
        ingredient = "minecraft:glowstone_dust",
    }, 
}

Potions.UNDERGARDEN = {{
        potion = "kubejs:brittleness", 
        base_potion = "kubejs:awkward", 
        ingredient = "undergarden:blood_globule",
    }, {
        potion = "kubejs:long_brittleness", 
        base_potion = "kubejs:brittleness", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_brittleness", 
        base_potion = "kubejs:brittleness", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:featherweight", 
        base_potion = "kubejs:awkward", 
        ingredient = "undergarden:veil_mushroom",
    }, {
        potion = "kubejs:long_featherweight", 
        base_potion = "kubejs:featherweight", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:strong_featherweight", 
        base_potion = "kubejs:featherweight", 
        ingredient = "minecraft:glowstone_dust",
    }, {
        potion = "kubejs:virulent_resistance", 
        base_potion = "kubejs:awkward", 
        ingredient = "undergarden:gloomgourd",
    }, {
        potion = "kubejs:long_virulent_resistance", 
        base_potion = "kubejs:virulent_resistance", 
        ingredient = "minecraft:redstone",
    }, {
        potion = "kubejs:glowing", 
        base_potion = "kubejs:awkward", 
        ingredient = "undergarden:droopvine_item",
    }, {
        potion = "kubejs:long_glowing", 
        base_potion = "kubejs:glowing", 
        ingredient = "minecraft:redstone",
    }, 
}

Potions.IRONS_SPELLBOOKS = {{
    potion = "kubejs:instant_mana_one", 
    base_potion = "kubejs:awkward", 
    ingredient = "irons_spellbooks:arcane_essence",
}, {
    potion = "kubejs:instant_mana_two", 
    base_potion = "kubejs:instant_mana_one", 
    ingredient = "minecraft:glowstone_dust",
}, {
    potion = "kubejs:instant_mana_three", 
    base_potion = "kubejs:instant_mana_two", 
    ingredient = "minecraft:amethyst_shard",
}, {
    potion = "kubejs:instant_mana_four", 
    base_potion = "kubejs:instant_mana_three", 
    ingredient = "minecraft:amethyst_cluster",
}}

Potions.ECOLOGICS = {{
    potion = "kubejs:sliding", 
    base_potion = "kubejs:awkward", 
    ingredient = "ecologics:penguin_feather",
}, {
    potion = "kubejs:long_sliding", 
    base_potion = "kubejs:sliding", 
    ingredient = "minecraft:redstone",
}}

Potions.ARS_NOUVEAU = {{
    potion = "kubejs:mana_regen_potion", 
    base_potion = "kubejs:awkward", 
    ingredient = "ars_nouveau:sourceberry_bush",
}, {
    potion = "kubejs:mana_regen_potion_long", 
    base_potion = "kubejs:mana_regen_potion", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:mana_regen_potion_strong", 
    base_potion = "kubejs:mana_regen_potion", 
    ingredient = "minecraft:glowstone_dust",
}, {
    potion = "kubejs:spell_damage_potion", 
    base_potion = "kubejs:awkward", 
    ingredient = "ars_nouveau:magebloom",
}, {
    potion = "kubejs:spell_damage_potion_long", 
    base_potion = "kubejs:spell_damage_potion", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:spell_damage_potion_strong", 
    base_potion = "kubejs:spell_damage_potion", 
    ingredient = "minecraft:glowstone_dust",
}, {
    potion = "kubejs:recovery_potion", 
    base_potion = "kubejs:awkward", 
    ingredient = "ars_nouveau:mendosteen_pod",
}, {
    potion = "kubejs:recovery_potion_long", 
    base_potion = "kubejs:recovery_potion", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:recovery_potion_strong", 
    base_potion = "kubejs:recovery_potion", 
    ingredient = "minecraft:glowstone_dust",
}, {
    potion = "kubejs:blasting_potion", 
    base_potion = "kubejs:awkward", 
    ingredient = "ars_nouveau:bombegranate_pod",
}, {
    potion = "kubejs:blasting_potion_long", 
    base_potion = "kubejs:blasting_potion", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:blasting_potion_strong", 
    base_potion = "kubejs:blasting_potion", 
    ingredient = "minecraft:glowstone_dust",
}, {
    potion = "kubejs:freezing_potion", 
    base_potion = "kubejs:awkward", 
    ingredient = "ars_nouveau:frostaya_pod",
}, {
    potion = "kubejs:freezing_potion_long", 
    base_potion = "kubejs:freezing_potion", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:freezing_potion_strong", 
    base_potion = "kubejs:freezing_potion", 
    ingredient = "minecraft:glowstone_dust",
}, {
    potion = "kubejs:shielding_potion", 
    base_potion = "kubejs:awkward", 
    ingredient = "ars_nouveau:bastion_pod",
}, {
    potion = "kubejs:shielding_potion_long", 
    base_potion = "kubejs:shielding_potion", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:shielding_potion_strong", 
    base_potion = "kubejs:shielding_potion", 
    ingredient = "minecraft:glowstone_dust",
}}

Potions.ARS_ELEMENTAL = {{
    potion = "kubejs:enderference_potion", 
    base_potion = "kubejs:awkward", 
    ingredient = "minecraft:twisting_vines",
}, {
    potion = "kubejs:enderference_potion_long", 
    base_potion = "kubejs:enderference_potion", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:shock_potion", 
    base_potion = "kubejs:awkward", 
    ingredient = "ars_elemental:flashpine_pod",
}, {
    potion = "kubejs:shock_potion_long", 
    base_potion = "kubejs:shock_potion", 
    ingredient = "minecraft:redstone",
}}

Potions.EIDOLON = {{
    potion = "kubejs:undeath", 
    base_potion = "kubejs:awkward", 
    ingredient = "eidolon:death_essence",
}, {
    potion = "kubejs:long_undeath", 
    base_potion = "kubejs:undeath", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:vulnerable", 
    base_potion = "kubejs:awkward", 
    ingredient = "eidolon:tattered_cloth",
}, {
    potion = "kubejs:long_vulnerable", 
    base_potion = "kubejs:vulnerable", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:strong_vulnerable", 
    base_potion = "kubejs:vulnerable", 
    ingredient = "minecraft:glowstone",
}, {
    potion = "kubejs:reinforced", 
    base_potion = "kubejs:awkward", 
    ingredient = "minecraft:nautilus_shell",
}, {
    potion = "kubejs:long_reinforced", 
    base_potion = "kubejs:reinforced", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:strong_reinforced", 
    base_potion = "kubejs:reinforced", 
    ingredient = "minecraft:glowstone",
}, {
    potion = "kubejs:anchored", 
    base_potion = "kubejs:awkward", 
    ingredient = "eidolon:warped_sprouts",
}, {
    potion = "kubejs:long_anchored", 
    base_potion = "kubejs:anchored", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:chilled", 
    base_potion = "kubejs:awkward", 
    ingredient = "eidolon:wraith_heart",
}, {
    potion = "kubejs:long_chilled", 
    base_potion = "kubejs:chilled", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:decay", 
    base_potion = "kubejs:awkward", 
    ingredient = "eidolon:withered_heart",
}, {
    potion = "kubejs:long_decay", 
    base_potion = "kubejs:decay", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:strong_decay", 
    base_potion = "kubejs:decay", 
    ingredient = "minecraft:glowstone",
}}

Potions.NATURALIST = {{
    potion = "kubejs:forest_dasher", 
    base_potion = "kubejs:awkward", 
    ingredient = "naturalist:antler",
}, {
    potion = "kubejs:long_forest_dasher", 
    base_potion = "kubejs:forest_dasher", 
    ingredient = "minecraft:redstone",
}, {
    potion = "kubejs:strong_forest_dasher", 
    base_potion = "kubejs:forest_dasher", 
    ingredient = "minecraft:glowstone_dust",
}}

Potions.POTIONS_MASTER = {{
    potion = "kubejs:coal_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedcoal_powder"
}, {
    potion = "kubejs:iron_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatediron_powder"
}, {
    potion = "kubejs:redstone_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedredstone_powder"
}, {
    potion = "kubejs:lapis_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedlapis_powder"
}, {
    potion = "kubejs:gold_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedgold_powder"
}, {
    potion = "kubejs:diamond_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinateddiamond_powder"
}, {
    potion = "kubejs:emerald_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedemerald_powder"
}, {
    potion = "kubejs:aluminum_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedaluminum_powder"
}, {
    potion = "kubejs:copper_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedcopper_powder"
}, {
    potion = "kubejs:tin_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedtin_powder"
}, {
    potion = "kubejs:nickel_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatednickel_powder"
}, {
    potion = "kubejs:uranium_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinateduranium_powder"
}, {
    potion = "kubejs:lead_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedlead_powder"
}, {
    potion = "kubejs:silver_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedsilver_powder"
}, {
    potion = "kubejs:zinc_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedzinc_powder"
}, {
    potion = "kubejs:osmium_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedosmium_powder"
}, {
    potion = "kubejs:quartz_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedquartz_powder"
}, {
    potion = "kubejs:bismuth_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedbismuth_powder"
}, {
    potion = "kubejs:crimsoniron_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedcrimsoniron_powder"
}, {
    potion = "kubejs:platinum_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedplatinum_powder"
}, {
    potion = "kubejs:netherite_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatednetherite_powder"
}, {
    potion = "kubejs:allthemodium_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedallthemodium_powder"
}, {
    potion = "kubejs:vibranium_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedvibranium_powder"
}, {
    potion = "kubejs:unobtainium_sight", 
    base_potion = "kubejs:mundane", 
    ingredient = "potionsmaster:calcinatedunobtainium_powder"
}}

Potions.DEEPER_DARKER = {{
    potion = "kubejs:sculk_affinity", 
    base_potion = "kubejs:awkward", 
    ingredient = "deeperdarker:soul_crystal"
}, {
    potion = "kubejs:long_sculk_affinity", 
    base_potion = "kubejs:sculk_affinity", 
    ingredient = "minecraft:redstone"
}}

Potions.AUTUMNITY = {{
    potion = "kubejs:extension", 
    base_potion = "kubejs:awkward", 
    ingredient = "autumnity:snail_goo"
}}

Potions.QUARK = {{
    potion = "kubejs:resilience", 
    base_potion = "kubejs:awkward", 
    ingredient = "quark:crab_shell"
}, {
    potion = "kubejs:long_resilience", 
    base_potion = "kubejs:resilience", 
    ingredient = "minecraft:redstone"
}, {
    potion = "kubejs:strong_resilience", 
    base_potion = "kubejs:resilience", 
    ingredient = "minecraft:glowstone_dust"
}}

return Potions
